# Sample configuration file for asv_bwrap

# Work directory (where output etc. goes), relative to this file
dir = "./workdir"

# Git repository url or path to upload results to.  This repository
# will be cloned (outside sandbox) and benchmark results and generated
# html will be copied to it and committed.  Results go to 'master'
# branch; html pages replaces 'gh-pages'.
#
# With --upload, results are uploaded.
#
# If not given, a local repository is used instead.
upload = "git@github.com:pv/numpy-bench.git"

# SSH deploy key for uploading results. Not available inside sandbox.
# If empty, not used.
ssh_key = "deploy-key"

# Hostname in sandbox. If not given, same as host.
hostname = "atom"

# List of files to copy to the sandbox directory (on each run)
copy_files = ["asv.conf.json", "machine.json"]

# List of directories and files to expose (read-only) inside the sandbox.
expose = ["/etc/resolv.conf",
          "/etc/nsswitch.conf",
          "/etc/alternatives",
          "/etc/pki",
          "/etc/ssl",
          "/usr",
          "/usr/local",
          "/bin",
          "/lib",
          "/lib64"]

#
# Bash scripts to run inside the sandbox, in a sandbox dir.  HOME
# etc. are set to point to the sandbox directory, and the filesystem
# namespace is temporary and separate from the host system, except for the
# /home/{sandbox,html,results} directories.
#

[scripts]

# To run before other scripts
preamble = """
set -e -o pipefail

export REPO_URL="https://github.com/numpy/numpy.git"
export REPO_SUBDIR="benchmarks"

source "$HOME/asv-bwrap-scripts/preamble1.sh"
export OPT="-O2 -g0 -fno-lto"
export FOPT="-O2 -g0 -fno-lto"
"""

# To run when setting up the sandbox the first time
setup = """
run python3 -mvenv env
source env/bin/activate
run pip install --upgrade "pip>=19" wheel
run pip install asv virtualenv Cython
"""

# Default run script
#
# The asv 'results' directory should be symlinked to /home/results,
# and asv html output should be copied to /home/html.
run = """
source "$HOME/env/bin/activate"
source "$HOME/asv-bwrap-scripts/run1.sh"
mv -f $HOME/machine.json $HOME/.asv-machine.json
prepare_asv
mv -f $HOME/asv.conf.json asv.conf.json
sed -i -e 's/class Benchmark(object):/class Benchmark(object):\\n    repeat = 1, 5, 2.0\\n    processes = 1/' benchmarks/common.py
run time asv "$@"
run time asv publish
copy_html
"""

