#!/bin/bash

if test -f qhull.pyx; then
    # Patch old Scipy sources for Cython >=0.28 compatibility
    sed -i -E -e '/^(Delaunay|Voronoi|ConvexHull)\.add_points\.__func__\.__doc__/d;' qhull.pyx
fi

$HOME/env/bin/cython.real "$@"
EXC=$?
if test "$EXC" != "0"; then
    # Fallback for old scipy versions...
    sed -i -e 's/cpdef long int tell(self):/cpdef long int tell(self) except -1:/' streams.pyx
    sed -i -e 's/cpdef long int tell(self):/cpdef long int tell(self) except -1:/' streams.pxd
    exec $HOME/.local/bin/cython.real "$@"
fi
exit 0
