#!/bin/bash
$HOME/env/bin/cython.real "$@"
EXC=$?
if test "$EXC" != "0"; then
    # Fallback for old scipy versions...
    sed -i -e 's/cpdef long int tell(self):/cpdef long int tell(self) except -1:/' streams.pyx
    sed -i -e 's/cpdef long int tell(self):/cpdef long int tell(self) except -1:/' streams.pxd
    exec $HOME/.local/bin/cython.real "$@"
fi
exit 0
